AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*
    - .bundle/*
    - vendor/cache/**/*
    - db/seeds.rb

Metrics/LineLength:
  Max: 110
  Exclude:
    - config/initializers/secret_token.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/s3.rb
    - Guardfile
    - db/seeds.rb
    - config/initializers/session_store.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  Enabled: false

MethodLength:
  Max: 15

Documentation:
  Enabled: false

PerlBackrefs:
  Enabled: false

StructInheritance:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/services/workflow_service.rb

Style/FrozenStringLiteralComment:
  Enabled: false
